### ISSUE TITLE
Add to cart not working without image upload

### ISSUE THREAD

**Issue by RemeJuan** [Drupalfarms/uc_attribute_files#7]
Set up this mod on a card website, during testing i completely forgot to test weather or not it worked in the even of the end user not uploading an image as the site has existing designs for all the items so the upload needs to simply be optional and tthe fact that its not marked as required made me assume it would simply work.

However in reality this unfortunately is not the case, the site wed.co.za has them setup under the puzzle cards section and unless you actually upload an image it generates the error that it only supports X file types, now i have tried the obvious of setting supported types tot he \* wild card but t hen it echos only supports %label%, is this a problem on the modules site or do i need to start tearing up a site to look for possible conflicts?

Thanks

**Comment by RemeJuan** [comment]
Anyone here?

**Comment by websiteexpress** [comment]
Same problem for me - in effect this has become required even when that is not desired. Will see if I can spot the issue...

**Comment by Orisian** [comment]
Anyone has solved this issue? The upload file for order in Ubercart has delayed my site's change to e-shop because of it's specific products for 1 year and after I found this module I could have finally change it. But now the problem is that you can't add to cart that item without uploading a file... and for my products is uploading not necessary, but it must be there for an option.

Tried to play with the .module file but my knowledge is poor...

So please if anyone has solved this, contact me pls.

Thanks
